AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Resources:
  MyLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./lambda_function/
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      Timeout: 60
      Events:
        ScheduledEvent:
          Type: Schedule
          Properties:
            Schedule: rate(10 minutes)
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref MyDynamoDBTable
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt MySNSTopic.TopicName

  MyDynamoDBTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: title
        Type: String

  MySNSTopic:
    Type: AWS::SNS::Topic

  MyAPIGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
