AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Online Hermes Inventory for AU

Resources:
  InventoryProfilerFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      # CodeUri: functions/hermes_profiler/
      # Handler: app.lambda_handler
      # Runtime: python3.9
      Timeout: 60
      Architectures:
        - x86_64
      Events:
        ScheduleEvent:
          Type: ScheduleV2
          Properties:
            ScheduleExpression: "rate(10 minutes)"
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DynamoDBTable
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt SNSTopic.TopicName
        - AmazonAPIGatewayInvokeFullAccess
      Environment:
        Variables:
          DYNAMODB_TABLE: !Ref DynamoDBTable
          API_GATEWAY_REGION1: !Ref APIGatewayRegion1
          # API_GATEWAY_REGION2: !If [DeployToRegion2, !Ref APIGatewayRegion2, ""]
          SNS_TOPIC_ARN: !Ref SNSTopic
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: functions/hermes_profiler/
      DockerTag: python3.9-v1

  APIGatewayRegion1:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      EndpointConfiguration:
        Type: REGIONAL
      OpenApiVersion: "3.0.1"
      Auth:
        DefaultAuthorizer: AWS_IAM
      DefinitionBody:
        openapi: "3.0.1"
        info:
          title: "APIGatewayRegion1"
        paths:
          /$default:
            x-amazon-apigateway-any-method:
              isDefaultRoute: true
              x-amazon-apigateway-integration:
                uri: "https://www.hermes.com/au/en/category/women/bags-and-small-leather-goods/bags-and-clutches/"
                httpMethod: "GET"
                type: "http_proxy"
                requestParameters:
                  integration.request.header.X-My-X-Forwarded-For: "'4.4.4.4'"
              responses: {}

  DynamoDBTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: item_id
        Type: String

  SNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: HermesInventoryAU
