AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Online Hermes Inventory for AU

Globals:
  Function:
    MemorySize: 512

Resources:
  InventoryProfilerFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Timeout: 60
      Architectures:
        - x86_64
      Events:
        ScheduleEvent:
          Type: ScheduleV2
          Properties:
            ScheduleExpression: "rate(10 minutes)"
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DynamoDBTable
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt SNSTopic.TopicName
        - AmazonAPIGatewayInvokeFullAccess
      Environment:
        Variables:
          DYNAMODB_TABLE: !Ref DynamoDBTable
          API_GATEWAY_REGION1: !Ref APIGatewayRegion1
          SNS_TOPIC_ARN: !Ref SNSTopic
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: functions/hermes_profiler/
      DockerTag: python3.9-v1

  APIGatewayRegion1:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      EndpointConfiguration:
        Type: REGIONAL
      OpenApiVersion: "3.0.1"
      Auth:
        DefaultAuthorizer: AWS_IAM
      DefinitionBody:
        openapi: "3.0.1"
        info:
          title: "APIGatewayRegion1"
        paths:
          /:
            get:
              x-amazon-apigateway-integration:
                uri: "https://www.hermes.com/au/en/category/women/bags-and-small-leather-goods/bags-and-clutches/"
                httpMethod: "GET"
                type: "http_proxy"
                requestParameters:
                  integration.request.header.X-My-X-Forwarded-For: "'4.4.4.4'"
                  integration.request.header.referer: "'https://www.hermes.com/au/en/'"
                responses: {}

  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: uuid
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: N
        - AttributeName: item_id
          AttributeType: S
      KeySchema:
        - AttributeName: uuid
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: ItemIdIndex
          KeySchema:
            - AttributeName: item_id
              KeyType: HASH
            - AttributeName: timestamp
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST

  SNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: HermesInventoryAU
